language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3

script:
  - phpize
  - ./configure --quiet
  - make
  - MODULES=`pwd`/modules/
  - php --version
  - SHOW_ONLY_GROUPS="FAIL,XFAIL,BORK,WARN,LEAK,SKIP" REPORT_EXIT_STATUS=1 php run-tests.php -n -d extension_dir=$MODULES -d extension=dom_varimport.so -q -x --show-diff
